### PR TITLE
mshtml/msxml3: Fix JavaScript dispatch, event handling, and XML parsing for Adobe installers

### PR DESCRIPTION
**Pull request by PhialsBasement**
Fixes Adobe Creative Cloud installer failing due to several Wine incompatibilities:

mshtml: Don't delegate dynamic DISPIDs to jscript (breaks JSObject bridge)
mshtml: Route event attributes through Wine's event system in IE9+ mode
mshtml: Compile event handler strings instead of storing them
mshtml: Fix NodeList exposing incorrect interfaces
msxml3: Wrap embedded XML declarations in CDATA (Windows tolerates these, libxml2 doesn't)

Enables Adobe CC installer to complete successfully, tested with Photoshop 2021 and 2025 installation

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @PhialsBasement, you've come across a downstream fork of wine. This pull request should be evaluated and merged upstream before considering if it should be backported to Proton.

**Comment by CypherpunkSamurai** [comment]
LGTM. create a pr at https://gitlab.winehq.org/wine/wine :)

**Comment by nonetrix** [comment]
Someone mind linking to the PR over on Winehq?

**Comment by MichaelMeoww** [comment]
Newbie Linux user here, how can I use the fix with my wine installation?

**Comment by nonetrix** [comment]
> Newbie Linux user here, how can I use the fix with my wine installation?

Not sure what you mean, but if you want to have at least the Photoshop installer to work not sure if it progresses further than that, you will need to learn how to compile Wine from source. I would just not bother unless you're up for an adventure

File: dlls/msxml3/domdoc.c [hunk 1]
```diff
@@ -499,11 +499,415 @@ static void sax_serror(void* ctx, const xmlError* err)
...
 }
 
+/* Check if ptr points to "<?xml" in UTF-8 or UTF-16LE format */
+static int is_xml_decl(const char *ptr, int len, int is_utf16)
+{
+    if (is_utf16)
+    {
+        /* UTF-16LE: each char is 2 bytes, second byte is 0 for ASCII */
+        if (len < 10) return 0;
+        return ptr[0] == '<' && ptr[1] == 0 &&
```
Comment (JacobBrownAustin) [inline dlls/msxml3/domdoc.c:509]: Why not use `wcsncmp` or something similar here?

File: dlls/msxml3/domdoc.c [hunk 2]
```diff
@@ -499,11 +499,415 @@ static void sax_serror(void* ctx, const xmlError* err)
...
+        return NULL;
+
+    dst = result;
+    /* Copy everything up to content_start */
+    for (p = ptr; p < content_start; p++)
+        *dst++ = *p;
+    /* Insert <![CDATA[ */
+    if (is_utf16)
+    {
+        *dst++ = '<'; *dst++ = 0;
```
Comment (JacobBrownAustin) [inline dlls/msxml3/domdoc.c:863]: Why not use swprintf or memcpy on UTF-16LE string literal?

**Comment by bartoszkosiorek** [comment]
Awensome work!

Unfortunately, the PR is without additional tests, which will cover these features.

The tests are must have, to be able to make sure that Wine implementation is working in the same way as Windows implementation.

It drastically prevents from regressions.

Test results are available at:
https://test.winehq.org/data/

The tests should be done in separate commit, before fix with `wine_todo`. It will show what is not working in previous implementation, and later what was fixed.

**Comment by alosslessdev** [comment]
> Someone mind linking to the PR over on Winehq?

https://gitlab.winehq.org/wine/wine/-/merge_requests/?sort=created_date&state=opened&first_page_size=20&page_after=eyJjcmVhdGVkX2F0IjoiMjAyNS0xMi0xMSAxNzoxMzo0MS42MDY0MzkwMDAgKzAwMDAiLCJpZCI6IjEyMzkzIn0 it has not been opened. Someone else will have to open it I guess

**Comment by FernandoMMuniz** [comment]
Hopefully it's submited to wine soon.
https://www.reddit.com/r/linux_gaming/comments/1qdgd73/comment/o07f40p/

**Comment by morgwai** [comment]
for Debian-13 users:
I've applied the patches to the latest version of my unofficial [ntsync-capable Wine-11 packages](https://wiki.debian.org/Wine/NtsyncHowto).

**Comment by ahydronous** [comment]
These patches are in staging for Wine 11.1: https://www.phoronix.com/news/Wine-Staging-11.1

**Comment by morgwai** [comment]
@ahydronous it's probably also worth to include 96cddf74 that was added after this PR was closed.

**Comment by PhialsBasement** [comment]
> These patches are in staging for Wine 11.1: https://www.phoronix.com/news/Wine-Staging-11.1

I think this is missing the collection fix (96cddf7) and the dropdown value fix (62449d6 and 984d780)

**Comment by morgwai** [comment]
@PhialsBasement the "dropdown value fix" patches fail to compile with the mainline Wine-11.0: any chance of moving your efforts from this declined Valve branch to the mainline?

the error just in case:
```
dlls/mshtml/omnavigator.c:546:25: error: initialization of ‘HRESULT (*)(struct constructor *)’ {aka ‘long int (*)(struct constructor *)’} from incompatible pointer type ‘HRESULT (*)(HTMLInnerWindow *, DispatchEx **)’ {aka ‘long int (*)(HTMLInnerWindow *, DispatchEx **)’} [-Wincompatible-pointer-types]
  546 |     .init_constructor = create_xml_serializer_ctor,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ActuallyTheOwner** [comment]
I am keeping an eye on developments with this, I think this is still very cool and would assume paint.net would be the next program to view for fixes as some older versions of that still run

**Comment by PhialsBasement** [comment]
> @PhialsBasement the "dropdown value fix" patches fail to compile with the mainline Wine-11.0: any chance of moving your efforts from this declined Valve branch to the mainline?
> 
> the error just in case:
> 
> ```
> dlls/mshtml/omnavigator.c:546:25: error: initialization of ‘HRESULT (*)(struct constructor *)’ {aka ‘long int (*)(struct constructor *)’} from incompatible pointer type ‘HRESULT (*)(HTMLInnerWindow *, DispatchEx **)’ {aka ‘long int (*)(HTMLInnerWindow *, DispatchEx **)’} [-Wincompatible-pointer-types]
>   546 |     .init_constructor = create_xml_serializer_ctor,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Im looking into this

**Comment by morgwai** [comment]
@PhialsBasement thanks for looking into this!

I should also note, that at some point there was renaming of var prefixes in `dlls/mshtml/mshtml_private.h` and `dlls/mshtml/omnavigator.c` (`PROT_` vs `OBJID_`), so the first compilation error I encountered was regarding that, after a trivial fix, the previously quoted one occurred.

**Comment by g-insn** [comment]
Can you please add some minimal wine tests as to what the installer basically does and expects? And then submit a MR on upstream (winehq), I don't see why these wouldn't go upstream if they prove to be correct. Besides avoiding regressions and proving correctness, tests make it easier for reviewers to also see how to suggest proper fixes.

**Comment by PhialsBasement** [comment]
> Can you please add some minimal wine tests as to what the installer basically does and expects? And then submit a MR on upstream (winehq), I don't see why these wouldn't go upstream if they prove to be correct. Besides avoiding regressions and proving correctness, tests make it easier for reviewers to also see how to suggest proper fixes.

Hey, what you have merged currently will only fix the Continue button working IIRC, the rest of the mshtml and xml patches are what made the whole thing do it's magic. First i want to rebase on wine proper and get it running before doing an MR, however, Just a quick question, on the WINE gitlab instance, some people said i needed to verify or something like that, but i've since lost the comment saying so, could you please give me a quick run down on what verify means?

**Comment by Alcaro** [comment]
> If you haven't validated your account yet, you'll need to file a [User Verification issue](https://gitlab.winehq.org/winehq/winehq/issues/new?issuable_template=User%20verification); see the [WineHQ Gitlab policies](https://gitlab.winehq.org/winehq/winehq/-/wikis/home) for more details. Once you have, your next step is to [fork a personal copy of Wine](https://gitlab.winehq.org/wine/wine/-/forks/new) and then clone that repository to your local system.

from https://gitlab.winehq.org/wine/wine/-/wikis/Submitting-Patches

**Comment by PhialsBasement** [comment]
> > If you haven't validated your account yet, you'll need to file a [User Verification issue](https://gitlab.winehq.org/winehq/winehq/issues/new?issuable_template=User%20verification); see the [WineHQ Gitlab policies](https://gitlab.winehq.org/winehq/winehq/-/wikis/home) for more details. Once you have, your next step is to [fork a personal copy of Wine](https://gitlab.winehq.org/wine/wine/-/forks/new) and then clone that repository to your local system.
> 
> from https://gitlab.winehq.org/wine/wine/-/wikis/Submitting-Patches

Thanks.

**Comment by PhialsBasement** [comment]
@g-insn The partial merge of these patches (de79e4f9f2b and a965a5c39fa) has introduced a regression. The changes to DISPATCH_PROPERTYGET | DISPATCH_METHOD handling in jscript/mshtml, cause ActiveScriptSite_OnScriptError failures that prevent the Adobe installer UI from even launching, wine-11.0 at least shows the UI. 

Reverting these two commits restores wine HEAD to the same behavior as wine-11.0 (installer launches but doesn't fully work). The original patches work as a complete set. just the dispatch changes without the rest of the event handling and DOM fixes breaks things worse than before.

Either revert de79e4f9f2b and a965a5c39fa to restore wine-11.0 baseline behavior and wait for me to submit the MR that pushes these patches all together or pull the remaining patches from this PR to get the full working implementation

Edit, i made a working mirror of wine with the patches reverted and the proper implementation for this implemented https://github.com/PhialsBasement/wine/commit/b4301d74c8f1dac2ee3012fbfe205255f096d0f9 I will write some tests and then get an MR up on the gitlab instance.

P.S @morgwai you can grab the patched msxml and mshtml from up here

**Comment by g-insn** [comment]
> Replying to https://github.com/ValveSoftware/wine/pull/310#issuecomment-3815527931

You can write tests without rebasing your patches, just to use what the installer expects. Of course, the tests will fail (without your patches), that's OK, you can even make them with `todo_wine`.

The commits you mentioned fixed another app that depended on that behavior, and tests confirm it's correct, at least with respect to such usage. I don't know what the installer does differently here, but a revert is clearly not the solution, we need to improve on it instead and fix the problem.

**Comment by morgwai** [comment]
@g-insn I was trying to find the answer in `dlls/mshtml/tests/dom.c` but cannot figure that out: which app was fixed by these commits?
Thanks!

**Comment by g-insn** [comment]
@morgwai It was for a CodeWeavers OEM. The point is that it came with tests to verify it's correct, at least for the limited case of what that app needed. But probably not fully in other cases that the installer expects, which is why I asked for tests. If tests pass on Windows reliably, it means the behavior is correct. Reverting it would also make those tests fail on wine.

**Comment by morgwai** [comment]
@g-insn, yes, I totally agree: just wanted to know what to mention when announcing the new packages, so that users know what to expect and can help with testing. Thanks! :)

**Comment by morgwai** [comment]
Debian-13 packages of Wine-11.0 with the new patch have been published (https://wiki.debian.org/Wine/NtsyncHowto)

The packages include patches from [Phial's repo](https://github.com/PhialsBasement/wine) submitted after 11.0 release touching any of `dlls/jscript`, `dlls/mshtml`, `dlls/msxml*` folders:
PhialsBasement/wine@a965a5c3
PhialsBasement/wine@de79e4f9
PhialsBasement/wine@f74d7c20
PhialsBasement/wine@6df98383
PhialsBasement/wine@b4301d74

**Comment by PhialsBasement** [comment]
@g-insn  I've found a fix that passes the tests while maintaining compatibility with applications like the Adobe installer.

The issue with commits a965a5c39fa and de79e4f9f2b was that they unconditionally converted DISPATCH_METHOD|DISPATCH_PROPERTYGET to DISPATCH_PROPERTYGET in ES5+ mode. This broke
applications that invoke methods with arguments - the METHOD flag was being stripped even for actual method calls.

The fix checks cArgs before deciding which flag to use:
```
if(wFlags == (DISPATCH_METHOD | DISPATCH_PROPERTYGET)) {
   if(pdp->cArgs > 0)
       wFlags = DISPATCH_METHOD;  /* Has arguments = method call */
   else
      wFlags = (This->ctx->version < SCRIPTLANGUAGEVERSION_ES5) ? DISPATCH_METHOD : DISPATCH_PROPERTYGET;
}
```
When arguments are passed (cArgs > 0), it's clearly a method invocation and should use DISPATCH_METHOD. Only when there are no arguments should we apply the ES5+ behavior of preferring
DISPATCH_PROPERTYGET for property access.

I also added the proper E_ACCESSDENIED return for METHOD|PROPERTYGET on function objects in quirks mode to match Windows behavior, which removes the todo_wine from test_method_vs_getter.

All the tests pass + installer still works

Changes: https://github.com/PhialsBasement/wine/compare/93f3d8ae9fa...c1141913436

**Comment by g-insn** [comment]
> Replying to https://github.com/ValveSoftware/wine/pull/310#issuecomment-3820954857

Thanks for your findings, though you still haven't added tests, but I created [MR 10004](https://gitlab.winehq.org/wine/wine/-/merge_requests/10004) for upstream winehq which should fix this. Please take a look at it to see what I meant by "adding tests", it's a pretty trivial fix, and this test does pass on Windows (that's how it's verified to be correct) while not passing with upstream Wine prior to this patch since it was broken. Again, thanks for the finding!

For the XML Serializer, please split it up into a completely separate PR/MR and open a MR on upstream wine, if possible. I suggest to split up the commits first so each commit only does one thing; generally, if you have commits that have something like "Do X and Y" in the title, it means it needs a split to two commits (one for X and one for Y). There's exceptions if it breaks existing behavior in the meantime (and/or tests) and you need both X and Y but that's not the case here.

For example, the first commit should just add the XMLSerializer constructor with tests only about the constructor's existence, `serializeToString` being a complete stub. A second or later commit should implement serializeToString with tests, and so on.

**Comment by morgwai** [comment]
> though you still haven't added tests,
(...)
> it's a pretty trivial fix

@g-insn  Thanks for your help and guidance with pushing it upstream! :)
Please bear in mind however that @PhialsBasement is working on this in his free time, which may be limited. Moreover, while adding tests is trivial to ppl already familiar with Wine's test infra, for new folks, it may require some time to dig into it first, which brings us back to the previous point ;-)

**Comment by Alcaro** [comment]
[It's been posted.](https://gitlab.winehq.org/wine/wine/-/merge_requests/10025)

Please keep the MR focused on the actual code; comments like "please get this into Wine 11.2" are off topic over there.
